#!/usr/bin/env ruby
# 1.9


=begin

  Project Feed Farm v.0.1
  
  -- [server] --
  run ./server.rb # will show live logs of the server
  
  -- [client] --
  telnet 127.0.0.1 54321
  
  - Title: Democracy Now! 2011-04-12 Tuesday
  - Description: Headlines for April 12, 2011; Nuclear Catastrophe in Japan “Not Equal to Chernobyl,
    But Way Worse”; Human Rights Concerns Continue After Capture of Ivory Coast Strongman Laurent
    Gbagbo; "I Am Willing to Give My Life": Bahraini Human Rights Activists Risk Lives to Protest
    U.S./Saudi-Backed Repression; The Army vs. the People?: A Democracy Now! Special Report from
    Egypt
  - Date 0000-00-00
  
  -- [snip] --
  
  Connection closed by foreign host.

  * UDP and TCP support *( just TCP for now )*
  * RSS 1/2 support
=end


